FROM kathara/base
RUN apt-get update && apt install --assume-yes ettercap-text-only iperf isc-dhcp-client isc-dhcp-server hping3 -y
RUN apt-get -y install python3-pip
RUN apt-get -y install python3-scapy